version: "3.8"

volumes:
  prometheus_data: {}
  clickhouse_data: {}
  clickhouse_logs: {}
  codexray_data: {}
  node_agent_data: {}
  cluster_agent_data: {}

services:
  codexray:
    restart: always
    image: ghcr.io/codifinary/codexray:latest
    pull_policy: always
    volumes:
      - codexray_data:/data
    ports:
      - 8080:8080
    command:
      - "--data-dir=/data"
      - "--bootstrap-prometheus-url=http://prometheus:9090"
      - "--bootstrap-refresh-interval=15s"
      - "--bootstrap-clickhouse-address=clickhouse:9000"
    depends_on:
      - clickhouse
      - prometheus

  node-agent:
    restart: always
    image: ghcr.io/codifinary/codexray-node-agent:latest
    pull_policy: always
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - node_agent_data:/data
    command:
      - "--collector-endpoint=http://codexray:8080"
      - "--cgroupfs-root=/host/sys/fs/cgroup"
      - "--wal-dir=/data"

  cluster-agent:
    restart: always
    image: ghcr.io/codifinary/codexray-cluster-agent
    pull_policy: always
    volumes:
      - cluster_agent_data:/data
    command:
      - "--coroot-url=http://codexray:8080"
      - "--metrics-scrape-interval=15s"
      - "--metrics-wal-dir=/data"
    depends_on:
      - codexray

  prometheus:
    restart: always
    image: prom/prometheus:v2.45.4
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - codexray-deploy_default

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:24.3
      environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=vizares
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - codexray-deploy_default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
